"""One node of an electricity system - dispatch as a linear program, then the
same thing said to PyPSA - written once for a machine.

REE 4301's Module 0 writes one problem three times: on paper, in gurobipy,
and in PyPSA, and shows they agree; then makes it a day long with a battery,
then makes capacity a decision. This module holds each of those constructions
once. ``dispatch_lp`` needs only gurobipy. Everything with ``network`` in its
name needs PyPSA, which is imported lazily so the rest of the package (and
the base test suite) does not depend on it - see the README in
``notebooks/12_energy_systems_pypsa/`` for the environment.

TABLES in ``data/raw/``:

    energy_generators.csv    the technologies: capacity, running cost,
                             annualised capital cost, a build ceiling
    energy_day_profiles.csv  24 hours of demand (MW) and solar availability
                             (per unit), GENERATED by ``day_profiles`` from
                             the two-bump formula Module 0 used; the script is
                             the source of truth and a test checks the file

The battery's four numbers - power, hours, one-way efficiency, standing
loss - are knobs the notebook names and passes in.
"""
from __future__ import annotations

import csv
import os
from dataclasses import dataclass, field

import numpy as np

from . import tolerance

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "data", "raw")
PROFILES_CSV = os.path.join(DATA_DIR, "energy_day_profiles.csv")
GENERATORS_CSV = os.path.join(DATA_DIR, "energy_generators.csv")

HOURS = np.arange(24)
DAYS_PER_YEAR = 365.0


# ------------------------------------------------------------------ tables

def day_profiles() -> dict:
    """Module 0's synthetic day: a 50 MW base, a morning bump at 8, the real
    peak at 19; solar a half-sine from 6 to 19. Rounded to what the CSV holds."""
    demand = 50 + 60 * np.exp(-((HOURS - 19) ** 2) / 12.0) + 18 * np.exp(-((HOURS - 8) ** 2) / 6.0)
    solar = np.clip(np.sin(np.pi * (HOURS - 6) / 13), 0, 1)
    return {"hour": [int(h) for h in HOURS],
            "demand_mw": [round(float(d), 4) for d in demand],
            "solar_pu": [round(float(s), 4) for s in solar]}


def write_day_profiles(path: str = PROFILES_CSV) -> None:
    p = day_profiles()
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["hour", "demand_mw", "solar_pu"])
        for h, d, s in zip(p["hour"], p["demand_mw"], p["solar_pu"]):
            w.writerow([h, d, s])


def load_day_profiles(path: str = PROFILES_CSV) -> dict:
    with open(path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return {"hour": [int(r["hour"]) for r in rows],
            "demand_mw": [float(r["demand_mw"]) for r in rows],
            "solar_pu": [float(r["solar_pu"]) for r in rows]}


@dataclass
class Technology:
    name: str
    p_nom: float                    # MW, the fleet as given
    marginal_cost: float            # $/MWh
    capital_cost: float             # $/MW/year, annualised
    p_nom_max: float                # MW, build ceiling when capacity is a decision
    varies: bool                    # follows the solar profile


def load_generators(path: str = GENERATORS_CSV) -> list:
    with open(path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return [Technology(r["technology"], float(r["p_nom_mw"]), float(r["marginal_cost"]),
                       float(r["capital_cost_per_mw_yr"]), float(r["p_nom_max_mw"]),
                       r["profile"] == "solar") for r in rows]


@dataclass
class Battery:
    p_nom: float = 40.0             # MW
    max_hours: float = 4.0          # energy = p_nom * max_hours
    efficiency: float = 0.927       # one way; round trip is the square
    standing_loss: float = 0.01     # fraction lost per hour, sitting
    marginal_cost: float = 0.01     # a token cost per MWh cycled


# ----------------------------------------------------------- the one hour

@dataclass
class Dispatch:
    objective: float
    p: dict                         # technology -> MW
    price: float                    # dual of the balance row, $/MWh
    label: str = ""


def dispatch_lp(techs: dict, demand: float, env=None) -> Dispatch:
    """``techs`` is {name: (available MW, $/MWh)}: min cost, meet demand,
    respect availability. The dual of the balance row is the price."""
    import gurobipy as gp
    with gp.Model(env=env) as m:
        tolerance.apply(m)
        p = m.addVars(techs.keys(), lb=0.0, name="p")
        m.setObjective(gp.quicksum(c * p[g] for g, (_, c) in techs.items()), gp.GRB.MINIMIZE)
        balance = m.addConstr(p.sum() == demand, name="balance")
        m.addConstrs((p[g] <= cap for g, (cap, _) in techs.items()), name="capacity")
        m.optimize()
        if m.Status != gp.GRB.OPTIMAL:
            raise RuntimeError("dispatch ended with status %d" % m.Status)
        return Dispatch(m.ObjVal, {g: p[g].X for g in techs}, balance.Pi, "gurobipy")


# ------------------------------------------------------------------ PyPSA

def _pypsa():
    try:
        import pypsa
    except ImportError as e:
        raise ImportError("PyPSA is not installed in this environment; see notebooks/12_energy_systems_pypsa/README.md") from e
    return pypsa


def solve_options(env=None) -> dict:
    """What every network here is solved with: Gurobi through linopy, silent,
    at the package's tightened tolerances so the agreement assertion is
    a claim the solve supports."""
    opts = dict(solver_name="gurobi", solver_options=dict(tolerance.GUROBI_PARAMS))
    if env is not None:
        opts["env"] = env
    return opts


def one_hour_network(techs: dict, demand: float):
    """The dispatch LP as a PyPSA network: one bus, one snapshot, a generator
    per technology, one load."""
    pypsa = _pypsa()
    n = pypsa.Network()
    n.set_snapshots([0])
    n.add("Bus", "node")
    for g, (cap, cost) in techs.items():
        n.add("Generator", g, bus="node", p_nom=cap, marginal_cost=cost)
    n.add("Load", "demand", bus="node", p_set=demand)
    return n


def day_network(profiles: dict, techs: list, battery: Battery | None, expand: bool = False,
                solar_capital_cost: float | None = None, days_per_year: float = DAYS_PER_YEAR):
    """Twenty-four hours. ``expand=True`` makes every generator's capacity a
    decision (Module 0's Part F) priced at capital_cost / days_per_year per
    day - the snapshots are one representative day, so a year of capital is
    spread over ``days_per_year`` of them; ``solar_capital_cost`` overrides
    the table's solar figure for the sweep. Both are knobs the notebook
    names and passes in."""
    pypsa = _pypsa()
    n = pypsa.Network()
    n.set_snapshots(profiles["hour"])
    n.add("Bus", "node")
    n.add("Load", "demand", bus="node", p_set=np.array(profiles["demand_mw"]))
    for t in techs:
        kw = dict(bus="node", marginal_cost=t.marginal_cost)
        if t.varies:
            kw["p_max_pu"] = np.array(profiles["solar_pu"])
        if expand:
            capex = solar_capital_cost if (t.varies and solar_capital_cost is not None) else t.capital_cost
            kw.update(p_nom_extendable=True, capital_cost=capex / days_per_year)
            if t.p_nom_max > 0:
                kw["p_nom_max"] = t.p_nom_max
        else:
            kw["p_nom"] = t.p_nom
        n.add("Generator", t.name, **kw)
    if battery is not None and battery.p_nom > 0:
        n.add("StorageUnit", "battery", bus="node", p_nom=battery.p_nom, max_hours=battery.max_hours,
              efficiency_store=battery.efficiency, efficiency_dispatch=battery.efficiency,
              standing_loss=battery.standing_loss, cyclic_state_of_charge=True,
              marginal_cost=battery.marginal_cost)
    return n


@dataclass
class DayResult:
    objective: float
    built: dict = field(default_factory=dict)     # technology -> MW, when capacity was a decision
    charging_hours: list = field(default_factory=list)
    discharging_hours: list = field(default_factory=list)
    peaker_hours: list = field(default_factory=list)
    prices: list = field(default_factory=list)


def solve_day(n, env=None) -> DayResult:
    n.optimize(**solve_options(env))
    prices = [float(v) for v in n.buses_t.marginal_price["node"]]
    built = {g: float(v) for g, v in n.generators.p_nom_opt.items()} if n.generators.p_nom_extendable.any() else {}
    charging = discharging = []
    if len(n.storage_units):
        p = n.storage_units_t.p["battery"]
        charging = [int(h) for h, v in zip(n.snapshots, p) if v < -tolerance.FEASIBILITY_ATOL]
        discharging = [int(h) for h, v in zip(n.snapshots, p) if v > tolerance.FEASIBILITY_ATOL]
    peaker = [int(h) for h, v in zip(n.snapshots, n.generators_t.p["peaker"]) if v > tolerance.FEASIBILITY_ATOL] \
        if "peaker" in n.generators.index else []
    return DayResult(float(n.objective), built, charging, discharging, peaker, prices)


def envelope_breakeven(profiles: dict, displaced_cost: float, days_per_year: float = DAYS_PER_YEAR) -> float:
    """The back-of-envelope value of one MW of solar: the energy it makes in a
    day times the running cost it displaces, times the days in a year.
    $/MW/year."""
    return float(np.sum(profiles["solar_pu"])) * displaced_cost * days_per_year


def solar_built(profiles: dict, techs: list, battery: Battery | None, solar_capital_cost: float, env=None,
                days_per_year: float = DAYS_PER_YEAR) -> float:
    """MW of solar the expansion model builds at this capital cost."""
    n = day_network(profiles, techs, battery, expand=True, solar_capital_cost=solar_capital_cost,
                    days_per_year=days_per_year)
    return solve_day(n, env).built["solar"]
